"""approach schema"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = '8c024e94d080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verb', sa.String(length=32), nullable=False),
    sa.Column('identity', sa.String(length=160), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('underwriter', sa.String(length=160), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=False),
    sa.Column('within_placing_authority', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('placement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('insured_name', sa.String(length=200), nullable=False),
    sa.Column('class_of_business', sa.String(length=80), nullable=False),
    sa.Column('inception_on', sa.Date(), nullable=False),
    sa.Column('handler', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('market_approach',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placement_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name='ck_market_approach_attempts_non_negative'),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['placement_id'], ['placement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('placement_id', 'market_id', 'stage', name='uq_market_approach_business_identity')
    )
    op.create_index('ix_market_approach_due', 'market_approach', ['state', 'due_at'], unique=False)
    op.create_table('approach_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approach_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approach_id'], ['market_approach.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approach_id', 'attempt_no', name='uq_approach_attempt_no')
    )
    op.create_table('carrier_reply',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approach_id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approach_id'], ['market_approach.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrier_reply')
    op.drop_table('approach_attempt')
    op.drop_index('ix_market_approach_due', table_name='market_approach')
    op.drop_table('market_approach')
    op.drop_table('placement')
    op.drop_table('market')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
